### ISSUE TITLE
Feature Request - respect notification inhibitors

### ISSUE THREAD

**Issue by peterhoeg** [mkcms/maildirwatch#5]
It's possible in KDE (and presumably also in GNOME) to set a "do not disturb" mode. It would be very elegant if `maildirwatch` could query the status over dbus in order to suppress notifications in case notifications are temporarily suspended.

This is how to query the status using `dbus-send`:

```sh
$ dbus-send --session \
  --dest=org.freedesktop.Notifications \
  --print-reply \
  /org/freedesktop/Notifications \
  org.freedesktop.DBus.Properties.Get \
  string:org.freedesktop.Notifications \
  string:Inhibited
```

Ideally of course maildirwatch wouldn't do this unconditionally but only when enabled using a `--honor-do-not-disturb-mode` or similar argument.

**Comment by mkcms** [comment]
Hi, thanks for the suggestion, indeed it sounds very useful.

Please see commit cf75c69bc875c7992f2f29a650a440cd421ca926. It adds the ability to specify a command which will be called before a notification is displayed and if it returns successfully, the notification is not displayed.

It'd be great if you could test that, then I'll push a new version to PyPI.

**Comment by peterhoeg** [comment]
Yep, that works, thanks!

**Comment by mkcms** [comment]
> Yep, that works, thanks!

I've pushed version 0.2.0 to PyPI, it can now be installed with `pip`.
